name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest-xl

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Clippy
        run: cargo clippy --all-targets

      - name: Test
        run: cargo test --all-targets
